### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by BatmanAoD** [josephscade/ffind#1]
Is there a reason this is not published on Crates.io? (I haven't published a crate there myself yet, but this seems like a useful tool).

**Comment by scrabsha** [comment]
Hello,
First I'd like to apologize for the time I took to answer to you.

This project was (is?) my very first rust project. The code is far from being usable. As you can see, I have stopped maintaining it.

However, I am okay with refactoring it in order to make "less derpy", and publish a first release if some people would benefit from it. Are you still using `ffind`?

**Comment by BatmanAoD** [comment]
That's okay! Thanks for responding anyway.

I've been using `fd-find`, which fits my needs well.
